fix(build): disable externalLiveBindings in rollup
`export * from '@testing-library/dom'` was causing issues where commonjs
imports would cause an error:

TypeError: Cannot set property fireEvent of #<Object> which has only a getter

Due to Rollbar adding a non-configurable property on `exports`

Setting `externalLiveBindings: false` uses simple assignment instead of
`Object.defineProperty`